/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NativeStoreOptions {
  dbPath?: string
  tableName?: string
  runtime?: string
  modelArchitecture?: string
  modelId?: string
  revision?: string
  onnxModelId?: string
  onnxPathInRepo?: string
}
export interface NativeQueryParams {
  limit?: number
  filter?: string
}
export interface NativeQueryResult {
  text: string
  metadataJson?: string
  distance?: number
  score?: number
}
export declare class NativeSemanticStore {
  constructor(options?: NativeStoreOptions | undefined | null)
  insert(text: string, metadataJson?: string | undefined | null): Promise<void>
  embed(text: string): Promise<Array<number>>
  embedBatch(texts: Array<string>): Promise<Array<Array<number>>>
  query(text: string, params?: NativeQueryParams | undefined | null): Promise<Array<NativeQueryResult>>
}
